name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: 3.12 # ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
      with:
        # Fetch all history for pushing fixes
        fetch-depth: 0
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
        
    - name: Run formatters and linters
      # Only run on Python 3.11 to avoid conflicting fixes
      if: matrix.python-version == '3.12'
      run: |
        black .
        isort .
        mypy faux_lingo
        
    - name: Commit formatting changes
      # Only run on Python 3.11 and if there are changes
      if: matrix.python-version == '3.12'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git diff --quiet || (git add . && git commit -m "Apply automatic formatting" && git push)
        
    - name: Run tests
      run: |
        pytest -vv --cov
